# Generated by Django 4.0.6 on 2022-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting1', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
